### ISSUE TITLE
GPUs requirements and training time

### ISSUE THREAD

**Issue by dongfengxijian** [zhengzangw/PCS-FUDA#1]
Thanks for sharing your work! How many GPUs and how long I need to train the PCS framework?

**Comment by zhengzangw** [comment]
One or two gpus with 16G memory will be enough. For each domain pair, it takes about 1h for office, 3h for officehome and over 1 day if you train on domainnet and visda.

**Comment by dongfengxijian** [comment]
> One or two gpus with 16G memory will be enough. For each domain pair, it takes about 1h for office, 3h for officehome and over 1 day if you train on domainnet and visda.

Thank you for replying！
