### ISSUE TITLE
The GPU usage is 0% but the memory usage is 1000MiB

### ISSUE THREAD

**Issue by ademjest** [zhengzangw/PCS-FUDA#13]
When I configured my environment according to requirement.txt and downloaded the officehome dataset, I got stuck at kmeans when I ran run.py. My cuda is 11.8.
The last result I wrote in log is below:
![屏幕截图 2024-06-08 192616](https://github.com/zhengzangw/PCS-FUDA/assets/119822948/af19e379-63d3-4f97-96d1-063bf66641fe)
And the running process does not end automatically and consumes memory. I wonder what the cause is, a memory leak?

**Comment by zhengzangw** [comment]
Not sure what is wrong. I guess one possible reason is your lib version is too new.

**Comment by ademjest** [comment]
Thanks very much! The problem has been solved. It is a version problem.
