### ISSUE TITLE
About the loss weight in config files.

### ISSUE THREAD

**Issue by Bostoncake** [zhengzangw/PCS-FUDA#4]
In `loss_params` domain of configs:

> "loss_params": {
    "thres_src": 0.99,
    "thres_tgt": 0.99,
    "temp": 0.1,
    "loss": [
      "cls-so",
      "proto-each",
      "I2C-cross",
      "semi-condentmax",
      "semi-entmin",
      "tgt-condentmax",
      "tgt-entmin"
    ],
    "weight": [1, 1, 1, 0.05, 0.05, 0.05, 0.05],
    "clus": {
      "kmeans_freq": 1,
      "type": ["each"],
      "n_k": 15,
      "k": [31, 62]
    }
  }

Would you please clarify the meanings for the statements in `loss` domain, such as `semi-condentmax`? Thanks!

**Comment by zhengzangw** [comment]
Statements in `loss` determine which losses to use.
`cls-so`: supervision from few-shot labels
`proto-each`: in-domain SSL loss
`I2C-cross`: cross-domain SSL loss
`semi-condentmax` `semi-entmin`: two parts of MIM on the unlabeled source domain
`tgt-condentmax` `tgt-entmin`: two parts of MIM on the unlabeled target domain
