### ISSUE TITLE
How many epochs for training on office, office-home and domainnet

### ISSUE THREAD

**Issue by liuyuchen6666** [zhengzangw/PCS-FUDA#5]
Thanks for your great job. I wonder How many epochs for training on office, office-home and domainnet? Is it 500 epochs in the config file?

**Comment by zhengzangw** [comment]
Thank you for your question. We do not train 500 epochs since we use early stop. A typical number of epochs we train is around 20 (see Figure 6 in the essay). The epoch may be more in DomainNet, but much less than 500.

**Comment by liuyuchen6666** [comment]
Thanks a lot.
