### ISSUE TITLE
About the training at visda17 and domainnet

### ISSUE THREAD

**Issue by jiaffly** [zhengzangw/PCS-FUDA#9]
Dear Zhengzang,
Thankes for your work.I want to ask you some questions about training at visda17datasets.In the beginning phase, the training automatically stops when the features of the source domain are calculated to be around 40%,I wonder if it accounts for the configuration file or visda is more large comparing office and office_home, or the memory of gpu is lacking(we have four gpus and each size is 12GB), since I modified configuration file based on the office and office_home file

**Comment by zhengzangw** [comment]
Visda17 is a large dataset and it may be so. You can use multiple GPUs and print out GPU memory from time to time to monitor your training.

**Comment by jiaffly** [comment]
Dear Zhengzang
Thanks for your suggestions，I will try it again.
